"""Write <psxrecomp>/runtime/include/overlay_codegen_hash.h before a game's pre-compile and build.

The header is normally a BUILD OUTPUT: CMake writes it during the game's native build
(runtime/hash_codegen.cmake). But two steps read it BEFORE that build runs:
  - Gradle's stageGameOverlays task (picks the pre-compiled code matching the hash),
  - compile_overlays.py (stamps the hash on every pre-compiled piece).
A freshly ported game has never been built, so it has no header and both steps fail
(FF7, 2026-10-05: "overlay_codegen_hash.h (The system cannot find the file specified)").

This computes the same value as hash_codegen.cmake (SHA-256 of the listed codegen sources,
concatenated in the order of runtime/codegen_hash_sources.cmake, first 8 hex digits) and
writes the header in the same format, so CMake later finds it unchanged.

With --recompiler it also checks that psxrecomp-game.exe was built from these same sources
(its --codegen-hash). A mismatch means the recompiler binary is stale: exit 2, change nothing.

Usage: codegen_hash.py <psxrecomp dir> [--recompiler <psxrecomp-game.exe>]
Prints the hash. Exit 0 ok, 1 error, 2 stale recompiler.
"""
import hashlib, os, re, subprocess, sys


def source_list(root):
    lst = os.path.join(root, 'runtime', 'codegen_hash_sources.cmake')
    text = open(lst, encoding='utf-8').read()
    text = '\n'.join(line.split('#', 1)[0] for line in text.splitlines())   # drop comments
    rel = re.findall(r'\$\{PSXRECOMP_CODEGEN_HASH_ROOT\}/([^\s)"]+)', text)
    if not rel:
        raise SystemExit(f'codegen_hash: no sources listed in {lst}')
    return [os.path.join(root, *r.split('/')) for r in rel]


def compute(root):
    h = hashlib.sha256()
    for f in source_list(root):
        if os.path.exists(f):            # hash_codegen.cmake skips missing files too
            # CMake's file(READ) turns CRLF into LF on Windows; hash what CMake hashes.
            h.update(open(f, 'rb').read().replace(b'\r\n', b'\n'))
    return h.hexdigest()[:8]


def main():
    args = sys.argv[1:]
    exe = None
    if '--recompiler' in args:
        i = args.index('--recompiler'); exe = args[i + 1]; del args[i:i + 2]
    if len(args) != 1:
        print(__doc__); return 1
    root = args[0]
    h8 = compute(root)
    if exe:
        out = subprocess.run([exe, '--codegen-hash'], capture_output=True, text=True, timeout=60)
        m = re.search(r'([0-9a-fA-F]{8})', out.stdout)
        got = m.group(1).lower() if m else '(none)'
        if got != h8:
            print(f'codegen_hash: STALE RECOMPILER: sources hash {h8}, {os.path.basename(exe)} says {got}')
            return 2
    content = ('/* AUTO-GENERATED by hash_codegen.cmake — do not edit, do not commit.\n'
               ' * Content hash of the recompiler codegen sources; folded into the overlay cache\n'
               ' * path so an emitter change never reuses a stale DLL. */\n'
               '#pragma once\n'
               f'#define PSX_OVERLAY_CODEGEN_HASH 0x{h8}u\n')
    hdr = os.path.join(root, 'runtime', 'include', 'overlay_codegen_hash.h')
    old = open(hdr, encoding='utf-8').read() if os.path.exists(hdr) else None
    if old != content:
        # Text mode, like CMake's file(WRITE) (CRLF on Windows), so CMake finds it unchanged.
        with open(hdr, 'w', encoding='utf-8') as f:
            f.write(content)
    print(h8)
    return 0


if __name__ == '__main__':
    sys.exit(main())
